version: "3.8"

name: daily-challenges

services:
  app:
    container_name: daily-challenges
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - .:/app
    restart: unless-stopped
